### ISSUE TITLE
Skull Cavern freezes time

### ISSUE THREAD

**Issue by Blackwigg** [huancz/EnergyTime#1]
I know this is kind a niche mod, but I simply love to play this game with it. It just makes the experience waaay less stressfull and I can plan every step I take without feeling like cheating. Now I finnally got to skull cavern (summer 1st) and just noticed that time simply doesn't pass when inside, it doesn't matter how much energy I spend so my only option there is disable the mod, but I would like to know another way to fix this, since I am enjoying stardew valley so much with this mod.

**Comment by huancz** [comment]
@Blackwigg 

I noticed the issue with Skull cavern too. But to be honest, this mod feels inherently unbalanced. The skull cavern problem is just small part of it. In normal game, bathhouse is balanced by the time you spend to get there and relax. With energytime, it becomes incredibly OP. Midgame, you have statue of blessing (blessing of energy). You can enchant your tools so their swings don't cost energy. Planting seeds should cost time but doesn't. Same with taking care of machine inputs and outputs...

I find I frequently need to either switch to vanilla time or just use the skip time key. Otherwise I would finish my day 6:10 AM. I treat it as improvement over the timestop mod I used before this. But you need some self restraint to keep the game interesting. It's probably better to do at least one characters (first two years) on unmodded game and then decide.

On practical side of things, I'm not the author, I just fixed what made the game unplayable in 1.6 (completely broken Calico desert). Skull cavern problem is just a glitch you can fix yourself by switching to vanilla time (at least I hope so, I'm not sure if I ever tried it. I'd just use timestop anyway if I was on serious cave dive. After several characters I think I earned some QoL).

I'll leave this open, but I can't promise I'll look into it.

**Comment by Blackwigg** [comment]
Thanks @huancz for fixing this mod, maybe I am the only one besides you testing this and that's actually not my first playthrough. The only reason I consider this mod crucial is because I am kinda a perfectionist, which comes in part from my ASD and the commitment I put while focusing, and can't support time pressure. I know this is suppose to be a relaxing game, but I can not relax with a counter at my side, while having 500h+ with this game my experience did not feel relaxing at all. I also like hard games and try to push myself to perfection, while also liking to take my time to complete everything. I recon that my biggest enemy is myself.

In vanilla I always reset the day at least 5 times before procceding with the next day and it felt like a stressfull experience. Then I used time stop mods just to think the next steps, and do some minor things but that always felt like cheating to me (I know that I am cheating anyways since I am using mods). The result is I never finished any saves to perfection or even got to ginger island. With the mod this is the first time I got hooked by the game. I also play with some restrains: Fishing with vanilla time, no bombs in the mines, unless I am playing with vanilla time, and I will probably ignore the energy cost enchantments. Maybe the only solution for skull caverns is to play with vanilla time, which I used to get to floor 80+ by the fall in vanilla, the way it was intended.

Regarding the skull cavern situation here is more info: There were no error messages in my SMAPI log, mod was probably working as intended. I don't have any mods that changes time passing. I also tried to change the energy/time multiplier all the way up 10x and time didn't pass when using my tools. Programing is not one of my skills, but i SUPOSE maybe skull cavern's different lenght of time passing doesn't support energy time method of time input from energy consumed?

I am just sharing my thoughts and don't require anything, thanks again for fixing this mod!

**Comment by huancz** [comment]
Turns out it was interesting enough problem to make me debug it. Time bonus in skull cavern was the obvious part, but mod was already adding that bonus. At least appeared to do so. Problem was, it was adding ExtraMillisecondsPerInGame**Minute**, but we need **10** in game minutes to pass. I finally realized that when I noticed that with some debug code, the clock hands in game actually go forward for a split second, then jump back.

Another thought, this means that with energytime, this bonus doesn't do anything. The stamina consumption per 10 game minutes is still the same. Maybe it should increase the stamina threshold to compensate, but I have no idea how much.

Anyway, fixed version for testing. Skull cavern works, I'm more interested in other locations.

[EnergyTime 1.4.2-unofficial.2-huancz.zip](https://github.com/user-attachments/files/16676261/EnergyTime.1.4.2-unofficial.2-huancz.zip)

**Comment by Blackwigg** [comment]
While I don't get much about coding, it totally makes sense to me. The mod isn't ballance around all things, so maybe it's fair to keep the same stamina consuption. People usually get there with gold tools and bombs anyway. I will tests if things get interesting playing with energy time in skull cavern.

**Comment by huancz** [comment]
I take it that no news is good news? Nothing broken? I'm not playing SDV currently, so I won't notice if there is a problem.

**Comment by Blackwigg** [comment]
Yep, I think we can close this.
